=== wjpremerlani/MatrixPilot_Vector_Roll/Tools/pyparam/ParameterDatabase.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema elementFormDefault="qualified" targetNamespace="ParameterDB" xmlns="ParameterDB" xmlns:xs="http://www.w3.org/2001/XMLSchema">



	<xs:complexType name="SerialisationFlags">
		<xs:sequence>
		<xs:element maxOccurs="16" minOccurs="1" name="serialisationFlag" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="UDBType">
		<xs:sequence>
			<xs:element name="typeName" type="xs:string"/>
			<xs:element name="sendFunction" type="xs:string"/>
			<xs:element name="setFunction" type="xs:string"/>
			<xs:element name="mavlinkType" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

  <xs:complexType name="UDBTypes">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="255" name="udbType" type="UDBType"/>
    </xs:sequence>
  </xs:complexType>
  
	<xs:complexType name="Parameter">
		<xs:sequence>
			<xs:element name="parameterName" type="ParamIdentifier"/>
			<xs:element name="udb_param_type" type="xs:string" />
			<xs:element name="variable_name" type="xs:string" default="NULL"/>
			<xs:element name="description" type="xs:string" default="no description" />
			<xs:element name="min" type="xs:string" default="0.0" />
			<xs:element name="max" type="xs:string" default="0.0" />
			
			<xs:element name="readonly" type="xs:boolean" default="true" />
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="Parameters">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="256" name="parameter" type="Parameter"/>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="ParameterBlock" >
		<xs:sequence>
			<xs:element name="blockName" type="xs:string" />
			<xs:element name="storage_area" type="xs:string"
				default="None" />
			<xs:element name="serialisationFlags"
				type="SerialisationFlags" />
			<xs:element name="externs" type="Externs" maxOccurs="1"
				minOccurs="0">
			</xs:element>
			<xs:element name="load_callback" type="xs:string" />
			<xs:element name="in_mavlink_parameters" type="xs:boolean" />
			<xs:element name="parameters" type="Parameters" />
			<xs:element name="description" type="xs:string"
				default="no description" />
		</xs:sequence>
	</xs:complexType>

	
	<xs:complexType name="ParameterBlocks" >
		<xs:sequence>
			<xs:element maxOccurs="32" minOccurs="1" name="parameterBlock" type="ParameterBlock"/>
		</xs:sequence>
	</xs:complexType>

	

	<xs:element name="ParameterDatabase">
		<xs:complexType>
			<xs:sequence>
                <xs:element name="dataStorageAreas" type="DataStorageAreas"></xs:element>
                <xs:element name="serialisationFlags"
					type="SerialisationFlags" />
				<xs:element name="udbTypes" type="UDBTypes" />
				<xs:element name="parameterBlocks"
					type="ParameterBlocks" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	

	<xs:complexType name="Externs">
		<xs:sequence>
			<xs:element name="externString" type="xs:string" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:simpleType name="ParamIdentifier">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"></xs:minLength>
			<xs:maxLength value="15"></xs:maxLength>

		</xs:restriction>
	</xs:simpleType>



	

	<xs:complexType name="DataStorageAreas">
		<xs:sequence>
			<xs:element name="dataStorageArea" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== wjpremerlani/MatrixPilot_Vector_Roll/Tools/pyparam/ParameterDatabase.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Aug 09 20:53:50 CEST 2011 -->


<ParameterDatabase
xmlns="ParameterDB"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="ParameterDB ParameterDatabase.xsd">
	<dataStorageAreas>
		<dataStorageArea>NULL</dataStorageArea>
		<dataStorageArea>FAILURE_DATALOG</dataStorageArea>
		<dataStorageArea>IMU_CALIB</dataStorageArea>
		<dataStorageArea>MAG_CALIB</dataStorageArea>
		<dataStorageArea>ANALOG_CALIB</dataStorageArea>
		<dataStorageArea>MIXER</dataStorageArea>
		<dataStorageArea>RTL_SETTINGS</dataStorageArea>
		<dataStorageArea>WAYPOINTS</dataStorageArea>
		<dataStorageArea>OSD_SETUP</dataStorageArea>
		<dataStorageArea>RADIO_TRIM</dataStorageArea>
		<dataStorageArea>CONTROL_GAINS</dataStorageArea>
		<dataStorageArea>THROTTLE_HEIGHT_OPTIONS</dataStorageArea>
		<dataStorageArea>AIRSPEED_OPTIONS</dataStorageArea>
	</dataStorageAreas>

<serialisationFlags>
	<serialisationFlag>ALL</serialisationFlag>
	<serialisationFlag>LOAD_AT_STARTUP</serialisationFlag>
	<serialisationFlag>LOAD_AT_REBOOT</serialisationFlag>
	<serialisationFlag>SAVE_AFTER_CAL</serialisationFlag>
	<serialisationFlag>STORE_WAYPOINTS</serialisationFlag>
	<serialisationFlag>STORE_CALIB</serialisationFlag>
	<serialisationFlag>SAVE_MISSION</serialisationFlag>
</serialisationFlags>


<udbTypes>
	<udbType>
	<typeName>UDB_TYPE_INT</typeName>
	<sendFunction>mavlink_send_param_int16</sendFunction>
	<setFunction>mavlink_set_param_int16</setFunction>
	<mavlinkType>MAVLINK_TYPE_INT32_T</mavlinkType>
	</udbType>
	<udbType>
	<typeName>UDB_TYPE_Q14</typeName>
	<sendFunction>mavlink_send_param_Q14</sendFunction>
	<setFunction>mavlink_set_param_Q14</setFunction>
	<mavlinkType>MAVLINK_TYPE_FLOAT</mavlinkType>
	</udbType>
	<udbType>
	<typeName>UDB_TYPE_PWTRIM</typeName>
	<sendFunction>mavlink_send_param_pwtrim</sendFunction>
	<setFunction>mavlink_set_param_pwtrim</setFunction>
	<mavlinkType>MAVLINK_TYPE_FLOAT</mavlinkType>
	</udbType>
	<udbType>
	<typeName>UDB_TYPE_GYROSCALE_Q14</typeName>
	<sendFunction>mavlink_send_param_gyroscale_Q14</sendFunction>
	<setFunction>mavlink_set_param_gyroscale_Q14</setFunction>
	<mavlinkType>MAVLINK_TYPE_FLOAT</mavlinkType>
	</udbType>
	<udbType>
	<typeName>UDB_TYPE_INT_CIRCULAR</typeName>
	<sendFunction>mavlink_send_int_circular</sendFunction>
	<setFunction>mavlink_set_int_circular</setFunction>
	<mavlinkType>MAVLINK_TYPE_INT32_T</mavlinkType>
	</udbType>
	<udbType>
	<typeName>UDB_TYPE_CM_AIRSPEED_TO_DM</typeName>
	<sendFunction>mavlink_send_dm_airspeed_in_cm</sendFunction>
	<setFunction>mavlink_set_dm_airspeed_from_cm</setFunction>
	<mavlinkType>MAVLINK_TYPE_INT32_T</mavlinkType>
	</udbType>
	<udbType>
	<typeName>UDB_TYPE_M_AIRSPEED_TO_DM</typeName>
	<sendFunction>mavlink_send_dm_airspeed_in_m</sendFunction>
	<setFunction>mavlink_set_dm_airspeed_from_m</setFunction>
	<mavlinkType>MAVLINK_TYPE_FLOAT</mavlinkType>
	</udbType>
	<udbType>
	<typeName>UDB_TYPE_M_AIRSPEED_TO_CM</typeName>
	<sendFunction>mavlink_send_cm_airspeed_in_m</sendFunction>
	<setFunction>mavlink_set_cm_airspeed_from_m</setFunction>
	<mavlinkType>MAVLINK_TYPE_FLOAT</mavlinkType>
	</udbType>
	<udbType>
	<typeName>UDB_TYPE_FRAME_ANGLERATE</typeName>
	<sendFunction>mavlink_send_frame_anglerate</sendFunction>
	<setFunction>mavlink_set_frame_anglerate</setFunction>
	<mavlinkType>MAVLINK_TYPE_INT32_T</mavlinkType>
	</udbType>
	<udbType>
	<typeName>UDB_TYPE_DCM_ANGLE</typeName>
	<sendFunction>mavlink_send_dcm_angle</sendFunction>
	<setFunction>mavlink_set_dcm_angle</setFunction>
	<mavlinkType>MAVLINK_TYPE_INT32_T</mavlinkType>
	</udbType>

</udbTypes>

<parameterBlocks>
	<parameterBlock>
		<blockName>PID_SETTINGS</blockName>
		<storage_area>CONTROL_GAINS</storage_area>
		<serialisationFlags>
			<serialisationFlag>LOAD_AT_STARTUP</serialisationFlag>
			<serialisationFlag>LOAD_AT_REBOOT</serialisationFlag>
			<serialisationFlag>STORE_CALIB</serialisationFlag>
		</serialisationFlags>
		<load_callback>NULL</load_callback>
		<in_mavlink_parameters>true</in_mavlink_parameters>
		<parameters>
			<parameter>
				<parameterName>PID_ROLLKP</parameterName>
				<udb_param_type>UDB_TYPE_Q14</udb_param_type>
				<variable_name>rollkp</variable_name>
				<description>Roll proporational gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			<parameter>
				<parameterName>PID_ROLLKD</parameterName>
				<udb_param_type>UDB_TYPE_GYROSCALE_Q14</udb_param_type>
				<variable_name>rollkd</variable_name>
				<description>Roll differential gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			<parameter>
				<parameterName>PID_YAWKPAIL</parameterName>
				<udb_param_type>UDB_TYPE_Q14</udb_param_type>
				<variable_name>yawkpail</variable_name>
				<description>yaw to aileron gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			<parameter>
				<parameterName>PID_YAWKDAIL</parameterName>
				<udb_param_type>UDB_TYPE_GYROSCALE_Q14</udb_param_type>
				<variable_name>yawkdail</variable_name>
				<description>yaw to aileron rate gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>

			<parameter>
				<parameterName>PID_PITCHGAIN</parameterName>
				<udb_param_type>UDB_TYPE_Q14</udb_param_type>
				<variable_name>pitchgain</variable_name>
				<description>PItch gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			<parameter>
				<parameterName>PID_PITCHKD</parameterName>
				<udb_param_type>UDB_TYPE_Q14</udb_param_type>
				<variable_name>pitchkd</variable_name>
				<description>Pitch rate gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			<parameter>
				<parameterName>PID_RUDELEVGAIN</parameterName>
				<udb_param_type>UDB_TYPE_Q14</udb_param_type>
				<variable_name>rudderElevMixGain</variable_name>
				<description>Roll differential gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			
			<parameter>
				<parameterName>PID_ROLLKPRUD</parameterName>
				<udb_param_type>UDB_TYPE_Q14</udb_param_type>
				<variable_name>rollkprud</variable_name>
				<description>Roll differential gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>

			<parameter>
				<parameterName>PID_YAWKPRUD</parameterName>
				<udb_param_type>UDB_TYPE_Q14</udb_param_type>
				<variable_name>yawkprud</variable_name>
				<description>Yaw to rudder gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			<parameter>
				<parameterName>PID_YAWKDRUD</parameterName>
				<udb_param_type>UDB_TYPE_GYROSCALE_Q14</udb_param_type>
				<variable_name>yawkdrud</variable_name>
				<description>Yaw to rudder rate gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			<parameter>
				<parameterName>PID_ROLLKPRUD</parameterName>
				<udb_param_type>UDB_TYPE_Q14</udb_param_type>
				<variable_name>rollkprud</variable_name>
				<description>Roll to rudder gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			<parameter>
				<parameterName>PID_ROLLKDRUD</parameterName>
				<udb_param_type>UDB_TYPE_Q14</udb_param_type>
				<variable_name>rollkdrud</variable_name>
				<description>Roll to rudder rate gain</description>
				<min>0.0</min>
				<max>0.5</max>
				<readonly>false</readonly>
			</parameter>
			
		</parameters>
		<description>PID Settings Block </description>
	</parameterBlock>


	<parameterBlock>
		<blockName>MAG_CALIB</blockName>
		<storage_area>MAG_CALIB</storage_area>
		<serialisationFlags>
			<serialisationFlag>LOAD_AT_STARTUP</serialisationFlag>
			<serialisationFlag>LOAD_AT_REBOOT</serialisationFlag>
			<serialisationFlag>STORE_CALIB</serialisationFlag>
		</serialisationFlags>
		<load_callback>NULL</load_callback>
		<in_mavlink_parameters>true</in_mavlink_parameters>
		<parameters>
			<parameter>
				<parameterName>MAG_CAL_RAW0</parameterName>
				<udb_param_type>UDB_TYPE_INT</udb_param_type>
				<variable_name>rawMagCalib[0]</variable_name>
				<description>magnetometer calibration raw 0</description>
				<min>-32767</min>
				<max>32767</max>
				<readonly>true</readonly>
			</parameter>
	
			<parameter>
				<parameterName>MAG_CAL_RAW1</parameterName>
				<udb_param_type>UDB_TYPE_INT</udb_param_type>
				<variable_name>rawMagCalib[1]</variable_name>
				<description>magnetometer calibration raw 0</description>
				<min>-32767</min>
				<max>32767</max>
				<readonly>true</readonly>
			</parameter>
	
			<parameter>
				<parameterName>MAG_CAL_RAW2</parameterName>
				<udb_param_type>UDB_TYPE_INT</udb_param_type>
				<variable_name>rawMagCalib[2]</variable_name>
				<description>magnetometer calibration raw 0</description>
				<min>-32767</min>
				<max>32767</max>
				<readonly>true</readonly>
			</parameter>
			<parameter>
				<parameterName>MAG_GAIN0</parameterName>
				<udb_param_type>UDB_TYPE_INT</udb_param_type>
				<variable_name>magGain[0]</variable_name>
				<description>magnetometer gain 0</description>
				<min>-32767</min>
				<max>32767</max>
				<readonly>true</readonly>
			</parameter>
	
			<parameter>
				<parameterName>MAG_GAIN1</parameterName>
				<udb_param_type>UDB_TYPE_INT</udb_param_type>
				<variable_name>magGain[1]</variable_name>
				<description>magnetometer gain 1</description>
				<min>-32767</min>
				<max>32767</max>
				<readonly>true</readonly>
			</parameter>
	
			<parameter>
				<parameterName>MAG_GAIN2</parameterName>
				<udb_param_type>UDB_TYPE_INT</udb_param_type>
				<variable_name>magGain[2]</variable_name>
				<description>magnetometer gain 2</description>
				<min>-32767</min>
				<max>32767</max>
